const foodIngredients: string[] = [
    "Flour",
    "Sugar",
    "Salt",
    "Butter",
    "Eggs",
    "Milk",
    "Yeast",
    "Baking powder",
    "Vanilla extract",
    "Cocoa powder",
    "Chocolate chips",
    "Olive oil",
    "Garlic",
    "Onion",
    "Tomatoes",
    "Basil",
    "Oregano",
    "Parmesan cheese",
    "Ground beef",
    "Chicken breast",
    "Lettuce",
    "Avocado",
    "Lemon",
    "Cilantro",
    "Soy sauce",
    "Rice",
    "Quinoa",
    "Black beans",
    "Corn",
    "Bell peppers",
    "Chili powder",
    "Cumin",
    "Paprika",
    "Turmeric",
    "Ginger",
    "Coconut milk",
    "Curry paste",
    "Peanut butter",
    "Honey",
    "Oats",
    "Almonds",
    "Raisins",
    "Maple syrup",
    "Greek yogurt",
    "Chia seeds",
    "Blueberries",
    "Bananas",
    "Spinach",
    "Kale",
    "Sesame seeds",
    "Sunflower seeds",
    "Quinoa",
    "Lentils",
    "Cucumber",
    "Carrots",
    "Zucchini",
    "Mushrooms",
  ];
  
  export default foodIngredients;